# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 700)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Ico/schedule.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(70, 91, 146);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_header = QtWidgets.QFrame(self.centralwidget)
        self.frame_header.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_header.setStyleSheet("")
        self.frame_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header.setObjectName("frame_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_header)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_error = QtWidgets.QFrame(self.frame_header)
        self.frame_error.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_error.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"border-radius: 7px;")
        self.frame_error.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setObjectName("frame_error")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_error)
        self.horizontalLayout_3.setContentsMargins(10, 3, 10, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_error = QtWidgets.QLabel(self.frame_error)
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.horizontalLayout_3.addWidget(self.label_error)
        self.pushButton_error = QtWidgets.QPushButton(self.frame_error)
        self.pushButton_error.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_error.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    background-image: url(:/Close_image/close_error.png);\n"
"    background-position: center;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(217, 217, 217);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 255, 127);\n"
"}")
        self.pushButton_error.setText("")
        self.pushButton_error.setObjectName("pushButton_error")
        self.horizontalLayout_3.addWidget(self.pushButton_error)
        self.horizontalLayout_2.addWidget(self.frame_error)
        self.verticalLayout.addWidget(self.frame_header)
        self.frame_body = QtWidgets.QFrame(self.centralwidget)
        self.frame_body.setStyleSheet("")
        self.frame_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_body.setObjectName("frame_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_body)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_content = QtWidgets.QFrame(self.frame_body)
        self.frame_content.setMaximumSize(QtCore.QSize(400, 550))
        self.frame_content.setStyleSheet("background-color: rgb(44, 69, 128);\n"
"border-radius: 10px;")
        self.frame_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.frame = QtWidgets.QFrame(self.frame_content)
        self.frame.setGeometry(QtCore.QRect(10, 20, 376, 134))
        self.frame.setMinimumSize(QtCore.QSize(376, 134))
        self.frame.setMaximumSize(QtCore.QSize(376, 134))
        self.frame.setStyleSheet("background-image: url(:/Logo_image/logo_login.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_avatar = QtWidgets.QFrame(self.frame_content)
        self.frame_avatar.setGeometry(QtCore.QRect(140, 170, 128, 128))
        self.frame_avatar.setMinimumSize(QtCore.QSize(128, 128))
        self.frame_avatar.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(44, 69, 128);\n"
"background-image: url(:/Login_image/addressbook_1.png);")
        self.frame_avatar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_avatar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_avatar.setObjectName("frame_avatar")
        self.lineEdit_username = QtWidgets.QLineEdit(self.frame_content)
        self.lineEdit_username.setGeometry(QtCore.QRect(60, 330, 280, 30))
        self.lineEdit_username.setMinimumSize(QtCore.QSize(280, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(245, 245, 245);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    border: 2px solid rgb(143, 59, 59);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(85, 170, 0);\n"
"}\n"
"\n"
"")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(self.frame_content)
        self.lineEdit_password.setGeometry(QtCore.QRect(60, 380, 280, 30))
        self.lineEdit_password.setMinimumSize(QtCore.QSize(280, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(245, 245, 245);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    border: 2px solid rgb(143, 59, 59);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(85, 170, 0);\n"
"}\n"
"")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_access = QtWidgets.QPushButton(self.frame_content)
        self.pushButton_access.setGeometry(QtCore.QRect(60, 440, 280, 50))
        self.pushButton_access.setMinimumSize(QtCore.QSize(280, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.pushButton_access.setFont(font)
        self.pushButton_access.setStyleSheet("QPushButton {\n"
"    background-color: rgb(102, 178, 247);\n"
"    border-radius: 5px; \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 69, 128);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 255, 127);\n"
"}")
        self.pushButton_access.setObjectName("pushButton_access")
        self.horizontalLayout.addWidget(self.frame_content)
        self.verticalLayout.addWidget(self.frame_body)
        self.frame_footer = QtWidgets.QFrame(self.centralwidget)
        self.frame_footer.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_footer.setStyleSheet("background-color: rgb(44, 69, 128);")
        self.frame_footer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_footer.setObjectName("frame_footer")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_footer)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_footer)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame_footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label_error.setText(_translate("MainWindow", "error"))
        self.lineEdit_username.setPlaceholderText(_translate("MainWindow", "Email or Username"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton_access.setText(_translate("MainWindow", "Acessar"))
        self.label.setText(_translate("MainWindow", "Criado por CCN Serviços em TI"))
import file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
